### ISSUE TITLE
SIFT  or  SURF

### ISSUE THREAD

**Issue by yyfyan081427** [JiawangBian/GMS-Feature-Matcher#19]
the code used ORB, But I want o use SIFT or SURF , and the matchs is zero ? need more changed?

**Comment by lovekittynine** [comment]
@yyfyan081427 @JiawangBian Hi, L also have try SIFT or SURF to detect keypoints and have modify BruteMatcher(cv2.NORM_L2) instead of Hamming.However, find zero matches???GMS is only used to filter false matches, but why when i changed the way of feature detection such as SIFT(stil set need to detect 10000 keypoints), it does not work anymore???边老师，请解答一下!谢谢!
